### ISSUE TITLE
Dialogue OAR conditions for elder

### ISSUE THREAD

**Issue by gs-oar** [gs-oar/gunslicer-oar#5]
https://github.com/gs-oar/gunslicer-oar/blob/1e9353276c2c397e5fc1c73cc105e8056c923356/Meshes/actors/character/animations/OpenAnimationReplacer/Gunslicer%20Animations%20OAR/Dialogue/config.json#L11-L14

should this be negated or is this the intended behavior?

**Comment by gs-oar** [comment]
@Nuascura does this currently mean the OAR conditions trigger this set for elder female NPCs who are not children? that seems off

**Comment by Nuascura** [comment]
ah, good catch. It's missing a negated tag for that elder condition. It should be
- NOT elder
- NOT child

**Comment by gs-oar** [comment]
fixed in a2deb0d
